% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 26-Apr-2017 21:40:15
%
% This script assumes these variables are defined:
%
%   BDP_CM - input data.
%   BDP_LabelBinary - target data.

%Training Dataset
Data_TrainingSource = BDP_CM';
Data_TrainingLabel = BDP_LabelBinary';

%Completely New Dataset
x1 = ASP_CM';
t1 = ASP_LabelBinary';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 65;
net = patternnet(hiddenLayerSize);
 
% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 30/100;
net.divideParam.valRatio = 35/100;
net.divideParam.testRatio = 35/100;


% Number of NetworkS to be trained. 
NumberANN = 20;

% Creating container for the NetworkS
nets = cell(1,NumberANN);

% Loop through index of the networks. 
for ANNIndex = 1:NumberANN
    fprintf('Training %d/%d\n', ANNIndex, hiddenLayerSize);
    % Train the Network
    %[net,tr] = train(net,Data_TrainingSource,Data_TrainingLabel);    
    nets{ANNIndex} = train(net, Data_TrainingSource, Data_TrainingLabel);    
end

% Performance cacluation on both data set. 
perfs = zeros(1, numNN);
y1Total = 0;
for ANNIndex = 1:numNN
  ANNatIndex = nets{ANNIndex};
  y1 = ANNatIndex(x1);
  perfs(ANNIndex) = mse(ANNatIndex, t1, y1);
  y1Total = y1Total + y1;
end
perfs
y1AverageOutput = y1Total / numNN;

perfAveragedOutputs = mse(nets{1}, t1, y1AverageOutput); 

% Test the Network
y = net(Data_TrainingSource);
e = gsubtract(Data_TrainingLabel,y);
performance = perform(net,Data_TrainingLabel,y)
tind = vec2ind(Data_TrainingLabel);
yind = vec2ind(y);
percentErrors = sum(tind ~= yind)/numel(tind);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
figure, plotperform(tr)
figure, plottrainstate(tr)
figure, ploterrhist(e)
figure, plotconfusion(Data_TrainingLabel,y)
figure, plotroc(Data_TrainingLabel,y)

